version: '3.8'

services:
  poumki_server:
    build: ./app
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_PORT:$NODE_MACHINE_PORT
    stdin_open: true
    tty: true
    volumes:
      - poumki-server-volume:/app/uploads

volumes: 
  poumki-server-volume: